apiVersion: v1 # the apiVersion should be v1
kind: Service
metadata:
  name: myapp-service # name of the service
spec:
  type: ClusterIP # this is the default type
  ports:
    # ports are defined in the perspective of the service.
    - targetPort: 8080 # this is the port that the application that runs in the pod is listening on
      port: 8080 # this is the port that the service is exposed
  # selector is used to link the service to a set of pods
  selector:
    # we can refer to the pod-definition.yml file and copy the labels section here
    app: myapp
    type: front-end
