apiVersion: v1
kind: Pod
# this labels helps you to identify these objects in later point in time.
# can be also used to filter pods in a way like frontend, backend etc.
metadata:
  name: myapp-pod
  labels:
    app: myapp
    type: front-end
spec:
  containers:
    - name: nginx-container
      image: nginx
